stages:
 # - test
  - deploy

# abc:
#   stage: test
#   image: 
#       name: hashicorp/terraform
#       entrypoint: [""]
#   script: 
#     - ls -la
#     - cd terraform
#     - terraform init
#     - terraform apply -auto-approve
#     - echo "EC2_PUBLIC_IP=$(terraform output -raw public_ipv4_address)" >> terraform.env

#   artifacts:
#     reports:
#       dotenv: terraform.env

xyz:
  stage: deploy 
  image: alpine
  before_script:
    - apk add --no-cache openssh
    - apk add git
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY"  | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - echo "Deployment and test starting .... " 
    - ssh ec2-user@
    - git pull
    - cd Projects/app/
    - pip  install -r requirements.txt
    - python app.py




