stages:
  - test
  - deploy

abc:
  stage: test
  image: python
  script: 
    - echo "hello from test stage"
  

xyz:
  stage: deploy 
  image: alpine
  before_script:
    - apk add --no-cache openssh
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY"  | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config


  script:
    - echo "Deployment and test starting .... " 
    - git pull
    - cd Projects/app/
    - pip  install -r requirements.txt
    - python app.py




