stages:
  - test
  - deploy

abc:
  stage: test
  image: 
      name: hashicorp/terraform
      entrypoint: [""]
  script: 
    - ls -la
    - cd terraform
    - terraform init

xyz:
  stage: deploy 
  image: alpine
  before_script:
    - apk add --no-cache openssh
    - apk add git
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY"  | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - echo "Deployment and test starting .... " 
    - ssh ec2-user@$EC2_PUBLIC_IP
    - git pull
    - cd Projects/app/
    - pip  install -r requirements.txt
    - python app.py




